// This file was autogenerated by `build_tools/src/config.rs
pub(crate) const DFLT_XKB_CONFIG_ROOT: &'static str = "/usr/share/X11/xkb";
pub(crate) const DFLT_XKB_CONFIG_EXTRA_PATH: &'static str = "/etc/xkb";
pub(crate) const DEFAULT_XKB_RULES: &'static str = "evdev";
pub(crate) const DEFAULT_XKB_MODEL: &'static str = "pc105";
pub(crate) const DEFAULT_XKB_LAYOUT: &'static str = "us";
pub(crate) const DEFAULT_XKB_VARIANT: &'static str = "";
pub(crate) const DEFAULT_XKB_OPTIONS: &'static str = "";
