// This file was autogenerated by `build_tools/src/config.rs
pub(crate) const DFLT_XKB_CONFIG_ROOT: &str = "/usr/share/X11/xkb";
pub(crate) const DFLT_XKB_CONFIG_EXTRA_PATH: &str = "/etc/xkb";
pub(crate) const DEFAULT_XKB_RULES: &str = "evdev";
pub(crate) const DEFAULT_XKB_MODEL: &str = "pc105";
pub(crate) const DEFAULT_XKB_LAYOUT: &str = "us";
pub(crate) const DEFAULT_XKB_VARIANT: &str = "";
pub(crate) const DEFAULT_XKB_OPTIONS: &str = "";
