name: Formatting and Clippy

on:
  pull_request:
  workflow_dispatch:

# Make sure CI fails on all warnings,
# including clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: format
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clippy
        run: cargo clippy --lib --tests --all-features
